### ISSUE TITLE
Weirdness under go v1.7

### ISSUE THREAD

**Issue by charl** [dominikh/go-staticcheck#13]
Since I upgraded to v1.7 staticcheck has been giving me inconsistent output:

``` go
$ staticcheck *.go

$ staticcheck *.go

$ staticcheck *.go
panic: inconsistent import:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer
previously imported as:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer
 [recovered]
  panic: inconsistent import:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer
previously imported as:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer


goroutine 1 [running]:
panic(0x660600, 0xc420476710)
  /usr/local/go/src/runtime/panic.go:500 +0x1a1
go/types.(*Checker).handleBailout(0xc42014e000, 0xc4201115e0)
  /usr/local/go/src/go/types/check.go:213 +0xae
panic(0x660600, 0xc420476710)
  /usr/local/go/src/runtime/panic.go:458 +0x243
golang.org/x/tools/go/gcimporter15.(*importer).declare(0xc42047a000, 0x7e71a0, 0xc420496fa0)
  /home/charl/projects/go/src/golang.org/x/tools/go/gcimporter15/bimport.go:184 +0x17c
golang.org/x/tools/go/gcimporter15.(*importer).obj(0xc42047a000, 0xfffffffffffffffb)
  /home/charl/projects/go/src/golang.org/x/tools/go/gcimporter15/bimport.go:212 +0x4ca
golang.org/x/tools/go/gcimporter15.BImportData(0xc420478000, 0xc420145c80, 0xc420456000, 0x17e40, 0x1fe00, 0xc42000e917, 0x5, 0x5, 0xc420292db8, 0xc420078990, ...)
  /home/charl/projects/go/src/golang.org/x/tools/go/gcimporter15/bimport.go:97 +0x3e8
golang.org/x/tools/go/gcimporter15.Import(0xc420145c80, 0xc42000e917, 0x5, 0x6b6485, 0x1, 0xc42040c690, 0x0, 0x0)
  /home/charl/projects/go/src/golang.org/x/tools/go/gcimporter15/gcimporter.go:178 +0x5d7
honnef.co/go/lint.importer.ImportFrom(0x6e0170, 0xc420145c80, 0xc42000e917, 0x5, 0x6b6485, 0x1, 0x0, 0x68dde0, 0x7e3501, 0x7f64994720f0)
  /home/charl/projects/go/src/honnef.co/go/lint/lint16.go:16 +0x58
honnef.co/go/lint.(*importer).ImportFrom(0xc42013d9f0, 0xc42000e917, 0x5, 0x6b6485, 0x1, 0x0, 0x0, 0x1, 0x0)
  <autogenerated>:5 +0x97
go/types.(*Checker).collectObjects(0xc42014e000)
  /usr/local/go/src/go/types/resolver.go:191 +0x826
go/types.(*Checker).checkFiles(0xc42014e000, 0xc42014a580, 0x8, 0x8, 0x0, 0x0)
  /usr/local/go/src/go/types/check.go:225 +0xaa
go/types.(*Checker).Files(0xc42014e000, 0xc42014a580, 0x8, 0x8, 0xc420145d70, 0xc420111738)
  /usr/local/go/src/go/types/check.go:218 +0x49
go/types.(*Config).Check(0xc42014a540, 0xc42012f260, 0x4, 0xc420014680, 0xc42014a580, 0x8, 0x8, 0xc42014c0a0, 0xc420147f60, 0x18, ...)
  /usr/local/go/src/go/types/api.go:344 +0x1a3
honnef.co/go/lint.(*Pkg).typeCheck(0xc4200146c0, 0x780000000044a9e0, 0x8)
  /home/charl/projects/go/src/honnef.co/go/lint/lint.go:256 +0x40a
honnef.co/go/lint.(*Pkg).lint(0xc4200146c0, 0x7fa900, 0x14, 0x14, 0xc420146b01, 0x4, 0xc42013e980)
  /home/charl/projects/go/src/honnef.co/go/lint/lint.go:127 +0x40
honnef.co/go/lint.(*Linter).LintFiles(0xc420111aa8, 0xc420111af8, 0xc420043aa8, 0xc420043ad0, 0x157b, 0x0, 0x0)
  /home/charl/projects/go/src/honnef.co/go/lint/lint.go:109 +0x710
honnef.co/go/lint/lintutil.(*runner).lintFiles(0xc420111e50, 0xc420094500, 0x8, 0x8)
  /home/charl/projects/go/src/honnef.co/go/lint/lintutil/util.go:114 +0x2a2
honnef.co/go/lint/lintutil.ProcessArgs(0x6bba2d, 0xb, 0x7fa900, 0x14, 0x14, 0xc420094400, 0x8, 0x8)
  /home/charl/projects/go/src/honnef.co/go/lint/lintutil/util.go:87 +0x3a7
main.main()
  /home/charl/projects/go/src/honnef.co/go/staticcheck/cmd/staticcheck/staticcheck.go:22 +0x257

$ staticcheck *.go
panic: inconsistent import:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer
previously imported as:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer
 [recovered]
  panic: inconsistent import:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer
previously imported as:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer


goroutine 1 [running]:
panic(0x660600, 0xc42041e8b0)
  /usr/local/go/src/runtime/panic.go:500 +0x1a1
go/types.(*Checker).handleBailout(0xc42013a000, 0xc4203d35d0)
  /usr/local/go/src/go/types/check.go:213 +0xae
panic(0x660600, 0xc42041e8b0)
  /usr/local/go/src/runtime/panic.go:458 +0x243
golang.org/x/tools/go/gcimporter15.(*importer).declare(0xc42013a540, 0x7e71a0, 0xc420484e10)
  /home/charl/projects/go/src/golang.org/x/tools/go/gcimporter15/bimport.go:184 +0x17c
golang.org/x/tools/go/gcimporter15.(*importer).obj(0xc42013a540, 0xfffffffffffffffb)
  /home/charl/projects/go/src/golang.org/x/tools/go/gcimporter15/bimport.go:212 +0x4ca
golang.org/x/tools/go/gcimporter15.BImportData(0xc420341c00, 0xc42012dc80, 0xc420444000, 0x17e40, 0x1fe00, 0xc42000f967, 0x5, 0x5, 0xc4203f4a90, 0x0, ...)
  /home/charl/projects/go/src/golang.org/x/tools/go/gcimporter15/bimport.go:97 +0x3e8
golang.org/x/tools/go/gcimporter15.Import(0xc42012dc80, 0xc42000f967, 0x5, 0x6b6485, 0x1, 0xc4203f6730, 0x0, 0x0)
  /home/charl/projects/go/src/golang.org/x/tools/go/gcimporter15/gcimporter.go:178 +0x5d7
honnef.co/go/lint.importer.ImportFrom(0x6e0170, 0xc42012dc80, 0xc42000f967, 0x5, 0x6b6485, 0x1, 0x0, 0x68dde0, 0x7e3501, 0x7fd83b14a0f0)
  /home/charl/projects/go/src/honnef.co/go/lint/lint16.go:16 +0x58
honnef.co/go/lint.(*importer).ImportFrom(0xc4201299e0, 0xc42000f967, 0x5, 0x6b6485, 0x1, 0x0, 0x4, 0x8, 0x0)
  <autogenerated>:5 +0x97
go/types.(*Checker).collectObjects(0xc42013a000)
  /usr/local/go/src/go/types/resolver.go:191 +0x826
go/types.(*Checker).checkFiles(0xc42013a000, 0xc420136580, 0x8, 0x8, 0x0, 0x0)
  /usr/local/go/src/go/types/check.go:225 +0xaa
go/types.(*Checker).Files(0xc42013a000, 0xc420136580, 0x8, 0x8, 0xc42012dd70, 0xc420105738)
  /usr/local/go/src/go/types/check.go:218 +0x49
go/types.(*Config).Check(0xc420136540, 0xc42011b5a8, 0x4, 0xc420014680, 0xc420136580, 0x8, 0x8, 0xc4201380a0, 0xc420135f60, 0x18, ...)
  /usr/local/go/src/go/types/api.go:344 +0x1a3
honnef.co/go/lint.(*Pkg).typeCheck(0xc4200146c0, 0x170000000044a9e0, 0x8)
  /home/charl/projects/go/src/honnef.co/go/lint/lint.go:256 +0x40a
honnef.co/go/lint.(*Pkg).lint(0xc4200146c0, 0x7fa900, 0x14, 0x14, 0xc420127301, 0x4, 0xc420130980)
  /home/charl/projects/go/src/honnef.co/go/lint/lint.go:127 +0x40
honnef.co/go/lint.(*Linter).LintFiles(0xc4203d3a98, 0xc4203d3ae8, 0xc420043aa8, 0xc420043ad0, 0x157b, 0x0, 0x0)
  /home/charl/projects/go/src/honnef.co/go/lint/lint.go:109 +0x710
honnef.co/go/lint/lintutil.(*runner).lintFiles(0xc4203d3e40, 0xc420080500, 0x8, 0x8)
  /home/charl/projects/go/src/honnef.co/go/lint/lintutil/util.go:114 +0x2a2
honnef.co/go/lint/lintutil.ProcessArgs(0x6bba2d, 0xb, 0x7fa900, 0x14, 0x14, 0xc420080400, 0x8, 0x8)
  /home/charl/projects/go/src/honnef.co/go/lint/lintutil/util.go:87 +0x3a7
main.main()
  /home/charl/projects/go/src/honnef.co/go/staticcheck/cmd/staticcheck/staticcheck.go:22 +0x257

$ staticcheck *.go

$ staticcheck *.go
panic: inconsistent import:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer
[...]
```

Simply running _staticcheck -version_ has similar behaviour:

```
$ staticcheck -version

$ staticcheck -version
flag provided but not defined: -version
Usage of staticcheck:
  staticcheck [flags] # runs on package in current directory
  staticcheck [flags] packages
  staticcheck [flags] directory
  staticcheck [flags] files... # must be a single package
Flags:
  -min_confidence float
      minimum confidence of a problem to print it (default 0.8)
  -tags build tags
      List of build tags

$ staticcheck -version
flag provided but not defined: -version
Usage of staticcheck:
  staticcheck [flags] # runs on package in current directory
  staticcheck [flags] packages
  staticcheck [flags] directory
  staticcheck [flags] files... # must be a single package
Flags:
  -min_confidence float
      minimum confidence of a problem to print it (default 0.8)
  -tags build tags
      List of build tags

$ staticcheck -version
flag provided but not defined: -version
Usage of staticcheck:
  staticcheck [flags] # runs on package in current directory
  staticcheck [flags] packages
  staticcheck [flags] directory
  staticcheck [flags] files... # must be a single package
Flags:
  -min_confidence float
      minimum confidence of a problem to print it (default 0.8)
  -tags build tags
      List of build tags

$ staticcheck -version
flag provided but not defined: -version
Usage of staticcheck:
  staticcheck [flags] # runs on package in current directory
  staticcheck [flags] packages
  staticcheck [flags] directory
  staticcheck [flags] files... # must be a single package
Flags:
  -min_confidence float
      minimum confidence of a problem to print it (default 0.8)
  -tags build tags
      List of build tags
panic: inconsistent import:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer
previously imported as:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer
 [recovered]
  panic: inconsistent import:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer
previously imported as:
  func bufio.NewWriterSize(w io.Writer, size int) *bufio.Writer


goroutine 1 [running]:
panic(0x660600, 0xc42036b710)
  /usr/local/go/src/runtime/panic.go:500 +0x1a1
go/types.(*Checker).handleBailout(0xc4200fc0e0, 0xc42028f3a8)
  /usr/local/go/src/go/types/check.go:213 +0xae
panic(0x660600, 0xc42036b710)
  /usr/local/go/src/runtime/panic.go:458 +0x243
golang.org/x/tools/go/gcimporter15.(*importer).declare(0xc4200fc460, 0x7e71a0, 0xc4203b4ff0)
  /home/charl/projects/go/src/golang.org/x/tools/go/gcimporter15/bimport.go:184 +0x17c
golang.org/x/tools/go/gcimporter15.(*importer).obj(0xc4200fc460, 0xfffffffffffffffb)
  /home/charl/projects/go/src/golang.org/x/tools/go/gcimporter15/bimport.go:212 +0x4ca
golang.org/x/tools/go/gcimporter15.BImportData(0xc4201fb9c0, 0xc42014aff0, 0xc420392000, 0x17e40, 0x1fe00, 0xc4201195d7, 0x5, 0x5, 0x1, 0xfa0000c420151d70, ...)
  /home/charl/projects/go/src/golang.org/x/tools/go/gcimporter15/bimport.go:97 +0x3e8
golang.org/x/tools/go/gcimporter15.Import(0xc42014aff0, 0xc4201195d7, 0x5, 0xc420013980, 0x37, 0xc4203447d0, 0x0, 0x0)
  /home/charl/projects/go/src/golang.org/x/tools/go/gcimporter15/gcimporter.go:178 +0x5d7
honnef.co/go/lint.importer.ImportFrom(0x6e0170, 0xc42014aff0, 0xc4201195d7, 0x5, 0xc420013980, 0x37, 0x0, 0x68dde0, 0x7e3501, 0x7f2a6e93f150)
  /home/charl/projects/go/src/honnef.co/go/lint/lint16.go:16 +0x58
honnef.co/go/lint.(*importer).ImportFrom(0xc42014e330, 0xc4201195d7, 0x5, 0xc420013980, 0x37, 0x0, 0x2, 0x4, 0x0)
  <autogenerated>:5 +0x97
go/types.(*Checker).collectObjects(0xc4200fc0e0)
  /usr/local/go/src/go/types/resolver.go:191 +0x826
go/types.(*Checker).checkFiles(0xc4200fc0e0, 0xc420147b00, 0x8, 0x8, 0x0, 0x0)
  /usr/local/go/src/go/types/check.go:225 +0xaa
go/types.(*Checker).Files(0xc4200fc0e0, 0xc420147b00, 0x8, 0x8, 0xc42014b0e0, 0xc4200e7510)
  /usr/local/go/src/go/types/check.go:218 +0x49
go/types.(*Config).Check(0xc420147ac0, 0xc420109880, 0x4, 0xc420013c00, 0xc420147b00, 0x8, 0x8, 0xc420145130, 0xc42014d840, 0x18, ...)
  /usr/local/go/src/go/types/api.go:344 +0x1a3
honnef.co/go/lint.(*Pkg).typeCheck(0xc420013c40, 0x800000000044a9e0, 0x8)
  /home/charl/projects/go/src/honnef.co/go/lint/lint.go:256 +0x40a
honnef.co/go/lint.(*Pkg).lint(0xc420013c40, 0x7fa900, 0x14, 0x14, 0xc420135601, 0x4, 0xc420113500)
  /home/charl/projects/go/src/honnef.co/go/lint/lint.go:127 +0x40
honnef.co/go/lint.(*Linter).LintFiles(0xc42028f870, 0xc42028f8c0, 0xc4200e7870, 0xc4200e7898, 0x762, 0x0, 0x0)
  /home/charl/projects/go/src/honnef.co/go/lint/lint.go:109 +0x710
honnef.co/go/lint/lintutil.(*runner).lintFiles(0xc42028fe40, 0xc4200fc000, 0x8, 0xe)
  /home/charl/projects/go/src/honnef.co/go/lint/lintutil/util.go:114 +0x2a2
honnef.co/go/lint/lintutil.(*runner).lintImportedPackage(0xc42028fe40, 0xc42005fc00, 0x0, 0x0)
  /home/charl/projects/go/src/honnef.co/go/lint/lintutil/util.go:162 +0x52a
honnef.co/go/lint/lintutil.(*runner).lintPackage(0xc42028fe40, 0xc42001269c, 0x1b)
  /home/charl/projects/go/src/honnef.co/go/lint/lintutil/util.go:134 +0xf2
honnef.co/go/lint/lintutil.ProcessArgs(0x6bba2d, 0xb, 0x7fa900, 0x14, 0x14, 0xc42000e820, 0x1, 0x1)
  /home/charl/projects/go/src/honnef.co/go/lint/lintutil/util.go:90 +0x32d
main.main()
  /home/charl/projects/go/src/honnef.co/go/staticcheck/cmd/staticcheck/staticcheck.go:22 +0x257
```

**Comment by dgryski** [comment]
I believe this is due to out-of-date /pkgs. Wipe them and make sure you're building with the newest dependencies for staticcheck: `go get -u honnef.co/go/staticcheck`

**Comment by charl** [comment]
On the money @dgryski.

I had to run _go get -u honnef.co/go/staticcheck/cmd/staticcheck_ to get things going again though.
